import type { IChampionship } from "src/types/championship";

import { Category } from "src/types/category";
import { MatchType } from "src/types/match-type";
import { MatchDays } from "src/types/match-days";
import { TournamentFormat } from "src/types/tournament-format";

export const _championshipList: IChampionship[] = [
  {
    id: "1",
    rowDate: "2025-03-26T15:00:00.000Z",
    championshipName: "Copa dos Campeões",
    championshipDescription: "## Campeonato Regional\n\nO torneio mais esperado do ano!",
    championshipBanner:
      "https://www.pontotel.com.br/local/wp-content/uploads/2022/05/imagem-corporativa.webp",
    startDate: "2025-04-01T00:00:00-03:00",
    endDate: "2025-04-30T00:00:00-03:00",
    matchDays: [MatchDays.SATURDAY, MatchDays.SUNDAY],
    startTime: "09:00",
    endTime: "17:00",
    state: "SP",
    city: "São paulo",
    category: Category.MALE,
    numberOfTeams: 16,
    minAge: 18,
    maxAge: 35,
    minPlayersPerTeam: 7,
    maxPlayersPerTeam: 12,
    matchType: MatchType.SEVEN_VS_SEVEN,
    tournamentFormat: TournamentFormat.POINTS,
  },
  {
    id: "2",
    rowDate: "2025-03-25T10:30:00.000Z",
    championshipName: "Torneio Feminino de Primavera",
    championshipDescription: "### Disputa acirrada entre os melhores times femininos!",
    championshipBanner: "https://example.com/images/banner-2.jpg",
    startDate: "2025-05-05T00:00:00-03:00",
    endDate: "2025-06-10T00:00:00-03:00",
    matchDays: [MatchDays.SUNDAY],
    startTime: "10:00",
    endTime: "14:00",
    state: "RJ",
    city: "Niterói",
    category: Category.FEMALE,
    numberOfTeams: 8,
    minAge: 16,
    maxAge: 30,
    minPlayersPerTeam: 5,
    maxPlayersPerTeam: 10,
    matchType: MatchType.FUTSAL,
    tournamentFormat: TournamentFormat.KNOCKOUT,
  },
  {
    id: "3",
    rowDate: "2025-03-20T08:15:00.000Z",
    championshipName: "Desafio Misto de Inverno",
    championshipDescription: "Partidas emocionantes com equipes mistas!",
    championshipBanner: "https://example.com/images/banner-3.jpg",
    startDate: "2025-07-10T00:00:00-03:00",
    endDate: "2025-08-15T00:00:00-03:00",
    matchDays: [MatchDays.WEDNESDAY, MatchDays.FRIDAY],
    startTime: "18:00",
    endTime: "22:00",
    state: "MG",
    city: "Belo Horizonte",
    category: Category.MIXED,
    numberOfTeams: 12,
    minAge: 20,
    maxAge: 40,
    minPlayersPerTeam: 6,
    maxPlayersPerTeam: 11,
    matchType: MatchType.SOCIETY,
    tournamentFormat: TournamentFormat.GROUPS,
  },
];
